INSERT INTO MEMBERS (MEMBER_ID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ROLE) VALUES
(1, 'AdminFirst', 'AdminLast', '012012012', 'admin@email.com', 'LIBRARIAN');

INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR, PUBLISHED_YEAR, STATUS) VALUES
(1, 'A Little Life', 'Hanya Yanagihara', '2015', 'AVAILABLE');