CREATE TABLE USERS(
	USERID INT AUTO_INCREMENT,
	USERNAME VARCHAR(20),
	ISDELETED BOOLEAN DEFAULT 0,
	ROLEID INT,
	PRIMARY KEY (USERID)
);

CREATE TABLE BOOK(
	BOOKID INT AUTO_INCREMENT,
	NAME VARCHAR(20),
	BOOKTYPE VARCHAR(20),
	STATUS VARCHAR(20),
	USERID INT,
	PRIMARY KEY (BOOKID)
);
